import {  CSSProperties } from "react";

export const Style = (): Record<string, CSSProperties> => ({
     container: {
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        background: 'linear-gradient(135deg, #f5f1f1 0%, #ac0c3c 100%)',
        fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
        padding: '20px',
        borderStyle:'none',
    },
    designercontainer: {
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        background: 'linear-gradient(135deg, #f5f1f1 0%, #ac0c3c 100%)',
        fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
        padding: '20px',
        columnGap:'20px',
        overflow: 'auto !important',
        maxHeight:'700px !important'
        
    },
    card: {
        background: 'white',
        borderRadius: '12px',
        boxShadow: '0 10px 40px rgba(0,0,0,0.1)',
        padding: '40px',
        maxWidth: '450px',
        width: '100%',
        borderStyle: 'none',
    },
    title: {
        fontSize: '28px',
        fontWeight: '700',
        color: '#333',
        marginBottom: '10px',
        textAlign: 'center',
    },
    subtitle: {
        fontSize: '14px',
        color: '#666',
        marginBottom: '30px',
        textAlign: 'center',
    },
    form: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
    },
    inputGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    label: {
        fontSize: '14px',
        fontWeight: '600',
        color: '#333',
    },
    input: {
        padding: '12px 16px',
        fontSize: '15px',
        border: '2px solid #e1e8ed',
        borderRadius: '8px',
        outline: 'none',
        transition: 'border-color 0.2s',
    },
    button: {
        padding: '14px 20px',
        fontSize: '16px',
        fontWeight: '600',
        color: 'white',
        background: 'linear-gradient(135deg, #e61f4a 0%, #764ba2 100%)',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        transition: 'transform 0.2s, box-shadow 0.2s',
        marginTop: '10px',
    },
    buttonSecondary: {
        background: 'white',
        color: '#02040f',
        border: '2px solid #f31919',
    },
    buttonDanger: {
        background: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    },
    link: {
        textAlign: 'center',
        marginTop: '20px',
        fontSize: '14px',
        color: '#666',
    },
    linkButton: {
        color: '#667eea',
        cursor: 'pointer',
        textDecoration: 'underline',
        fontWeight: '600',
    },
    error: {
        background: '#fee',
        color: '#c33',
        padding: '12px',
        borderRadius: '6px',
        fontSize: '14px',
        marginBottom: '20px',
        border: '1px solid #fcc',
    },
    success: {
        background: '#efe',
        color: '#3c3',
        padding: '12px',
        borderRadius: '6px',
        fontSize: '14px',
        marginBottom: '20px',
        border: '1px solid #cfc',
    },
    userInfo: {
        background: '#f8f9fa',
        padding: '20px',
        borderRadius: '8px',
        marginBottom: '20px',
    },
    userInfoItem: {
        display: 'flex',
        justifyContent: 'space-between',
        padding: '10px 0',
        borderBottom: '1px solid #e1e8ed',
    },
    userInfoLabel: {
        fontWeight: '600',
        color: '#666',
    },
    userInfoValue: {
        color: '#333',
    },
    buttonGroup: {
        display: 'flex',
        gap: '10px',
        flexWrap: 'wrap',
    },
    loading: {
        textAlign: 'center',
        fontSize: '18px',
        color: 'white',
    },
});